--
-- PostgreSQL database dump
--

\restrict sjtJptLtSiM52h8bHNTB9hp765MzRfLWPOOwM7FSLd5zufcW74fDH5V151uJVLJ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('5962f19b-ab8a-4b54-9ecb-2d41a362c9f1', 'local-representation', 'shield-check', 'Local Representation', 'On-the-ground presence and accountable representation so your company has a trusted voice inside Iraq at all times.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-covered-market.jpg', '["Multi-year opportunities and government-facing projects require sustained, in-country engagement across approval stages — something most international teams cannot maintain from abroad.", "We provide ongoing local representation, keeping your opportunities aligned with the relevant authorities and partners as they move through each stage, and surfacing issues early enough for you to respond before they become delays."]', '[{"title": "Ongoing Local Presence", "description": "A consistent, accountable point of contact for your company inside Iraq."}, {"title": "Stakeholder Continuity", "description": "Maintaining relationships with government and commercial counterparts across long project timelines."}, {"title": "Early Issue Escalation", "description": "Flagging procedural or relationship risks before they turn into delays."}]', 2, '2026-07-07 12:26:32.816912+00', '2026-07-07 12:29:16.80685+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('e09978f6-166b-4542-a43e-8d71625059a7', 'partner-search', 'handshake', 'Partner Search', 'Identification and vetting of local partners, distributors, and joint-venture candidates aligned with your commercial goals.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-baghdad-2023.jpg', '["Finding a local partner from outside Iraq usually means relying on introductions of uncertain quality — we replace that with a structured search and vetting process built around your specific commercial and compliance criteria.", "We source candidate partners, screen them against commercial capacity and compliance standing, and stay involved through negotiation to help structure terms that protect your long-term interests."]', '[{"title": "Candidate Sourcing", "description": "Building a shortlist of potential partners, distributors, or joint-venture candidates."}, {"title": "Commercial & Compliance Screening", "description": "Vetting candidates against capacity, track record, and compliance standing."}, {"title": "Negotiation Support", "description": "Structuring terms designed for a durable, long-term partnership rather than a single deal."}]', 3, '2026-07-07 12:26:33.006346+00', '2026-07-07 12:29:18.113378+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('76e088cb-f76a-478c-a66b-c40191166771', 'government-liaison', 'landmark', 'Government Liaison', 'Structured engagement with ministries, provincial authorities, and public entities to keep your project moving through official channels.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-baghdad-medical-city.jpg', '["Projects that touch government approval chains move at the pace of the relationship behind them — without structured local engagement, even a strong proposal can stall at the first procedural hurdle.", "We manage structured engagement with the ministries, provincial authorities, and public entities relevant to your project, keeping approvals moving and giving you visibility into where things actually stand."]', '[{"title": "Stakeholder Mapping", "description": "Identifying the specific ministries and public entities relevant to your project."}, {"title": "Approval Chain Management", "description": "Keeping your project moving through the official channels it depends on."}, {"title": "Status Visibility", "description": "Giving you a clear, honest view of where approvals stand and what''s next."}]', 4, '2026-07-07 12:26:33.193793+00', '2026-07-07 12:29:19.42202+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('c0e298a7-7032-4b07-8630-5961025b0ea2', 'feasibility-research', 'flask-conical', 'Feasibility & Market Research', 'Rigorous, data-backed studies that quantify demand, competition, and risk before capital is committed.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-erbil-expressway.jpg', '["Capital allocation decisions deserve more than desk research built on assumptions — we combine demand modeling, competitive analysis, and on-the-ground verification to give you a study you can actually act on.", "Our feasibility studies quantify market demand and regulatory risk specific to Iraq, and flag the risk factors that will need active management rather than leaving them as footnotes."]', '[{"title": "Demand Quantification", "description": "Modeling realistic market demand based on verified, on-the-ground data."}, {"title": "Competitive Landscape Analysis", "description": "Mapping existing competitors and their actual market position."}, {"title": "Regulatory Risk Assessment", "description": "Identifying the compliance and regulatory risks specific to your sector and structure."}]', 5, '2026-07-07 12:26:33.3806+00', '2026-07-07 12:29:20.957598+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('8ed801b5-131a-4235-b2dd-c5a0d68393da', 'commercial-advisory', 'briefcase', 'Commercial Advisory', 'Ongoing strategic counsel on pricing, positioning, and negotiation as your presence in Iraq matures.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-construction-iraq.jpg', '["As your presence in Iraq matures, the questions shift from market entry to sustained performance — pricing discipline, competitive positioning, and negotiation leverage that holds up over multiple deal cycles.", "We provide ongoing strategic counsel through this stage, drawing on continuous market and sector visibility rather than a one-time assessment."]', '[{"title": "Pricing & Positioning Review", "description": "Ongoing counsel on how your pricing and positioning compare against the local competitive set."}, {"title": "Negotiation Support", "description": "Advisory support through commercial negotiations with partners, distributors, or public entities."}, {"title": "Continuous Market Visibility", "description": "Keeping you informed on sector and competitive shifts relevant to your strategy."}]', 6, '2026-07-07 12:26:33.57097+00', '2026-07-07 12:29:22.771941+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('3e39e5b5-2d86-41b0-8c75-5481acf9137a', 'tender-intelligence', 'radar', 'Tender Intelligence', 'Continuous tracking of public and private tenders across priority sectors, filtered to the opportunities that match your capability.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-baghdad-skyline.jpg', '["Public procurement in Iraq runs through a mix of federal ministries, provincial authorities, and state-owned enterprises, each with its own tendering calendar and documentation requirements — treating tender tracking as a one-off search rather than a continuous discipline is the most common reason qualified bidders miss opportunities.", "We maintain a continuously updated tender pipeline across your priority sectors, scored against your actual capability and past win patterns, so you see strong opportunities with enough lead time to bid properly."]', '[{"title": "Continuous Tender Monitoring", "description": "Tracking tenders across ministries, provincial authorities, and state-owned enterprises in your sectors."}, {"title": "Fit & Win-Probability Scoring", "description": "Filtering opportunities against your actual technical and commercial capability."}, {"title": "Bid-Ready Lead Time", "description": "Surfacing strong matches early enough to prepare a properly qualified submission."}]', 1, '2026-07-07 12:26:32.630227+00', '2026-07-07 12:29:15.814049+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('9b8360a2-3190-43d4-9013-07017fedd04c', 'distribution-partnerships', 'truck', 'Distribution & Strategic Partnerships', 'Design and oversight of distribution networks and long-term strategic alliances built for sustained market share.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-erbil-expressway.jpg', '["Expanding distribution across Iraq''s provinces without overextending logistics costs or losing control of service quality requires a deliberately sequenced model, not an all-at-once rollout.", "We design distribution networks that balance provincial coverage against realistic costs, and build in incentive structures designed to keep partners engaged for the long term."]', '[{"title": "Network Design", "description": "Structuring distribution coverage sequenced against realistic logistics costs."}, {"title": "Partner Incentive Structuring", "description": "Building agreements designed to keep distribution partners engaged long-term."}, {"title": "Ongoing Oversight", "description": "Monitoring network performance and partner alignment as your footprint expands."}]', 7, '2026-07-07 12:26:33.761166+00', '2026-07-07 12:29:23.057581+00');
INSERT INTO public.services (id, slug, icon, title, description, image_url, body, highlights, sort_order, created_at, updated_at) VALUES ('4b5e211b-68a9-48b8-8234-56e43779b940', 'market-entry', 'compass', 'Market Entry', 'Structured entry roadmaps that translate Iraq''s regulatory, commercial, and cultural landscape into a clear plan of action.', 'https://asdobnhxvnihgwbkzdrt.supabase.co/storage/v1/object/public/media/seed/photo-baghdad-tigris.jpg', '["Entering the Iraqi market without a structured plan usually means losing the first year to avoidable missteps — the wrong legal structure, an unqualified first partner, or a commercial approach that doesn''t fit how business actually gets done locally.", "We build phased entry roadmaps that sequence legal setup, local registration, government relationship-building, and initial commercial targets, so the first twelve months have clear, achievable milestones rather than an open-ended search."]', '[{"title": "Entry Structure Design", "description": "Recommending the legal and operating structure that fits your commercial goals and risk tolerance."}, {"title": "Regulatory Roadmap", "description": "Sequencing the registration, licensing, and compliance steps required before you can operate."}, {"title": "First-Year Milestone Plan", "description": "Setting realistic, sequenced commercial targets for your first twelve months in-market."}]', 0, '2026-07-07 12:26:32.425679+00', '2026-07-07 12:54:16.597145+00');


--
-- PostgreSQL database dump complete
--

\unrestrict sjtJptLtSiM52h8bHNTB9hp765MzRfLWPOOwM7FSLd5zufcW74fDH5V151uJVLJ

